<?php
if(Mage::getStoreConfig('stasevi4_banner/general/sbenable') == true){?>
	<?php $arr = Mage::getStoreConfig('stasevi4_banner/images');?>
	<div class="floatmenu <?php echo  Mage::getStoreConfig('stasevi4_banner/general/bfloat') == 'left' ? 'fleft' : 'fright'; ?>">
		<ul>
			<?php for($i=1; $i<count($arr); $i++){?>				
			    <?php if(array_key_exists('image'. $i, $arr) && $arr['image'. $i] <> '' ){?>
						<?php if(array_key_exists('image'. $i .'_link', $arr) && $arr['image'. $i .'_link'] <> '' ){?>
							<li><a href="<?php echo $arr['image'. $i .'_link'];?>" target="<?php echo  Mage::getStoreConfig('stasevi4_banner/general/blinktarget')?>"><img src='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'stasevi4/'.$arr['image'. $i ]  ; ?>'/></a></li>
						<?php }else{?>
							<li><img src='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'stasevi4/'.$arr['image'. $i ]  ; ?>'/></li>
						<?php }?>
				<?php }?>
			<?php }?>	
		</ul>
	</div>
<?php }?>